---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(readxl)
library(survey)
library(srvyr)
```

```{r}
nychvs <- read_rds("../../data/output/nychvs/nychvs2017.rds")
nyc311 <- read_rds("../../data/output/nyc311/02-nyc311_complaintXsubboro.rds")
pumas <- read_excel("../../data/input/linking/nyc_puma_neighborhood.xls")
```

create an aptotriate design object that contains the data variables and the replication weights metadata needed for valid estimation
```{r}
svy <- svrepdesign(variables = nychvs[ ,seq(19)], 
                    repweights = nychvs[ ,paste0("FW", seq(80))],
                    weights = ~hhweight,
                    combined.weights=TRUE,
                    type="Fay",
                    rho = (1-1/sqrt(4)),
                    scale = 4/80,
                    rscales = rep(1,80),
                    data = nychvs) %>%
      as_survey_rep()
```

```{r}
alpha <- .05/(nrow(pumas)*7)
zscore <- qnorm(1-alpha/2)
```

```{r}
nhst <- function(df_svy = svy, df_311 = nyc311, issue_type){
  issue_quo <- enquo(issue_type)
    
  df_svy %>%
  filter(renter, !! issue_quo) %>%
  group_by(geo_id2) %>%
  summarise(tot = survey_total(!! issue_quo)) %>%
  mutate(lower = tot-zscore*tot_se,
         upper = tot+zscore*tot_se) %>%
  full_join(df_311, by = "geo_id2") %>%
  mutate(conclusion = case_when(!! issue_quo < lower ~ "underreported_to_311",
                                !! issue_quo > upper ~ "overreported_to_311",
                              TRUE ~ "within_expectation")) %>%
  left_join(pumas, by = c("geo_id2" = "PUMA5ID")) %>%
  select(geo_id2:upper, conclusion:PUMA_2010)
}
```


```{r issue_stairway}
obj <-
svy %>%
filter(renter, issue_stairway) %>%
mutate(geo_id2 = as.factor(geo_id2)) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_stairway)) %>%
mutate(lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("stair"), contains("tot"), lower, upper) %>%
mutate(same = issue_stairway >= lower & issue_stairway <= upper,
       conclusion = case_when(issue_stairway < lower ~ "underreported_to_311",
                            issue_stairway > upper ~ "overreported_to_311")) %>%
filter(same == FALSE | is.na(same)) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany")

issue_stairway <- nhst(issue_type = issue_stairway) %>% mutate(issue = "stairway")
```

```{r issue_floors}
obj <-
svy %>%
filter(renter, issue_floors) %>%
mutate(geo_id2 = as.factor(geo_id2)) %>%
group_by(geo_id2) %>%
summarise(floors_tot = survey_total(issue_floors)) %>%
mutate(lower = floors_tot-zscore*floors_tot_se,
       upper = floors_tot+zscore*floors_tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("floors"), lower, upper) %>%
mutate(same = issue_floors >= lower & issue_floors <= upper,
       conclusion = case_when(issue_floors < lower ~ "underreported_to_311",
                            issue_floors > upper ~ "overreported_to_311")) %>%
filter(same == FALSE | is.na(same)) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany")

issue_floors <- nhst(issue_type = issue_floors) %>% mutate(issue = "floors")
```

```{r issue_toilet}
obj <-
svy %>%
filter(renter, issue_toilet) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_toilet)) %>%
mutate(lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("toilet"), contains("tot"), lower, upper) %>%
mutate(conclusion = case_when(issue_toilet < lower ~ "underreported_to_311",
                            issue_toilet > upper ~ "overreported_to_311")) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany")

issue_toilet <- nhst(issue_type = issue_toilet) %>% mutate(issue = "toilet")
```

```{r issue_heat}
obj <-
svy %>%
filter(renter, issue_heat) %>%
mutate(geo_id2 = as.factor(geo_id2)) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_toilet)) %>%
mutate(lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("heat"), contains("tot"), lower, upper) %>%
mutate(same = issue_heat >= lower & issue_heat <= upper,
       conclusion = case_when(issue_heat < lower ~ "underreported_to_311",
                            issue_heat > upper ~ "overreported_to_311")) %>%
filter(same == FALSE | is.na(same)) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany")

issue_heat <- nhst(issue_type = issue_heat) %>% mutate(issue = "heat")
```

```{r issue_pests}
obj <-
svy %>%
filter(renter, issue_pests) %>%
mutate(geo_id2 = as.factor(geo_id2)) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_pests)) %>%
mutate(lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("pests"), contains("tot"), lower, upper) %>%
mutate(same = issue_pests >= lower & issue_pests <= upper,
       conclusion = case_when(issue_pests < lower ~ "underreported_to_311",
                            issue_pests > upper ~ "overreported_to_311")) %>%
filter(same == FALSE | is.na(same)) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany")

issue_pests <- nhst(issue_type = issue_pests) %>% mutate(issue = "pests")
```

```{r issue_plasterpaint}
obj <-
svy %>%
filter(renter, issue_plasterpaint) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_plasterpaint)) %>%
mutate(issue = "issue_plasterpaint", 
       lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
mutate(conclusion = case_when(issue_plasterpaint < lower ~ "underreported_to_311",
                            issue_plasterpaint > upper ~ "overreported_to_311",
                            TRUE ~ "within_expectation")) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID")) %>%
select(geo_id2:upper, conclusion:PUMA_2010)


issue_plasterpaint <- nhst(issue = issue_plasterpaint) %>% mutate(issue = "plasterpaint") %>% View()
table(obj$conclusion, useNA = "ifany")

```

```{r issue_leak}
obj <-
svy %>%
filter(renter, issue_leak) %>%
mutate(geo_id2 = as.factor(geo_id2)) %>%
group_by(geo_id2) %>%
summarise(tot = survey_total(issue_leak)) %>%
mutate(lower = tot-zscore*tot_se,
       upper = tot+zscore*tot_se) %>%
full_join(nyc311, by = "geo_id2") %>%
select(geo_id2, contains("leak"), contains("tot"), lower, upper) %>%
mutate(same = issue_leak >= lower & issue_leak <= upper,
       conclusion = case_when(issue_leak < lower ~ "underreported_to_311",
                            issue_leak > upper ~ "overreported_to_311")) %>%
filter(same == FALSE | is.na(same)) %>%
left_join(pumas, by = c("geo_id2" = "PUMA5ID"))

table(obj$conclusion, useNA = "ifany") 

issue_leak <- nhst(issue = issue_leak) %>% mutate(issue = "leak") %>% View()
```


