---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(RSocrata)
```

```{r}
data_dir <- c("../data/input/nychvs/")
data_files <- list.files(data_dir)
data_files

database <- paste0(data_dir, data_files) %>%
            map(read_csv)

names(database) <- str_extract(data_files, "NYCHVS [0-9]{4}") %>%
                   tolower() %>%
                   str_remove(" ")

colnames(database$nychvs2017)

View(database$nychvs2017)
database$nychvs2017[1,] %>% t()

table(database$nychvs2017$sba, useNA = "ifany")

database$nychvs2017 %>%
group_by(sba) %>%
summarise(n()) %>%
View

database$nychvs2017 %>%
group_by(sba) %>%
summarise(n()) %>%
View

database$nychvs2017 %>%
group_by(borough, sba) %>%
summarise(n()) %>%
View
```


```{r query311}
# df311 <- read.socrata("https://data.cityofnewyork.us/resource/fhrw-4uyv.json")

# df <- read.socrata(
#   "https://data.cityofnewyork.us/resource/fhrw-4uyv.csv",
#   app_token =  Sys.getenv("app_token"),
#   email     = Sys.getenv("email_address"),
#   password  = Sys.getenv("secret_token"))
# 
# df <- read.socrata(
#   "https://data.cityofnewyork.us/resource/877v-uy6n")
# colnames(df311)

df <- read_csv("../data/input/nyc311/2017_311complaints.csv") #%>%
      # filter(`Agency Name` == "Department of Housing Preservation and Development")
table(df$`Agency Name`, useNA = "ifany")
table(df$`Complaint Type`, useNA = "ifany")
table(df$Descriptor, useNA = "ifany")

df %>%
group_by(`Complaint Type`, Descriptor) %>%
summarise() %>%
arrange(`Complaint Type`, Descriptor) %>%
View()

df %>%
filter(`Agency Name` %in% c("Condo or CoOp Unit", 
                            "Senior Citizen Rent Increase Exemption Unit", 
                            "Department of Buildings", "DOHMH")) %>%
group_by(`Agency Name`, `Complaint Type`, Descriptor) %>%
summarise() %>%
View()
```

